# Generated by Django 3.0.8 on 2020-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(0, 'Information'), (1, 'Warning'), (2, 'Error'), (3, 'Critical')], null=True),
        ),
    ]
