# Generated by Django 3.0.8 on 2020-07-07 17:05

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200707_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-date_time',)},
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Suspend'), (3, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='text',
            field=django_quill.fields.QuillField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
    ]
