# Generated by Django 3.1.4 on 2020-12-09 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_issue_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='likes',
            field=models.ManyToManyField(related_name='issue_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
